project:
  type: book
  output-dir: docs

book:
  title: "Social Experiments with oTree and Python"
  author: "Moinul Islam"
  date: "1/1/2024"
  chapters:
    - index.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - chapter_5.qmd
    - chapter_6.qmd
    - chapter_7.qmd
    - chapter_8.qmd
    - chapter_9.qmd
    - chapter_10.qmd
    - chapter_11.qmd
    - chapter_12.qmd
    #- chapter_13.qmd
    #- chapter_14.qmd
    #- chapter_15.qmd
    - references.qmd

bibliography: social_experiment.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

